baseURL = 'https://sbom-insights.netlify.app/'
title = 'SBOM Insights'
languageCode = 'en-us'
theme = 'PaperMod'
[pagination]
pagerSize = 10

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
# googleAnalytics = 'G-ZWMS311EG2' # Deprecated - moved to params
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = 'production'
title = 'SBOM Insights'
description = 'Everything about Software Bill of Materials - Best practices, tools, and industry insights'
keywords = ['SBOM', 'Software Bill of Materials', 'Supply Chain Security', 'CycloneDX', 'SPDX', 'Open Source Security']
author = 'SBOM Community'
images = ['/logo.png']
DateFormat = 'January 2, 2006'
copyright = '© 2025 Interlynk.io and Contributors | [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)'
googleAnalytics = 'G-ZWMS311EG2'
defaultTheme = 'auto'
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShareButtons = ['x', 'linkedin', 'reddit', 'ycombinator']
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[params.assets]
favicon = '/favicon.ico'
favicon16x16 = '/favicon-16x16.png'
favicon32x32 = '/favicon-32x32.png'
apple_touch_icon = '/apple-touch-icon.png'
safari_pinned_tab = '/safari-pinned-tab.svg'

[params.label]
text = 'SBOM Insights'
icon = '/apple-touch-icon.png'
iconHeight = 35

[params.profileMode]
enabled = false
title = 'SBOM Insights'
subtitle = 'Your guide to Software Bill of Materials'
imageUrl = ''
imageWidth = 120
imageHeight = 120
imageTitle = 'SBOM Insights'

[[params.profileMode.buttons]]
name = 'Posts'
url = 'posts'

[[params.profileMode.buttons]]
name = 'Contributors'
url = 'contributors'



[params.analytics.google]
SiteVerificationTag = ''

[params.analytics.bing]
SiteVerificationTag = ''

[params.analytics.yandex]
SiteVerificationTag = ''

[params.cover]
hidden = false
hiddenInList = false
hiddenInSingle = false

[params.editPost]
URL = 'https://github.com/YOUR-REPO/sbom-blog/content'
Text = 'Suggest Changes'
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ['title', 'permalink', 'summary', 'content']

[[menu.main]]
identifier = 'home'
name = 'Home'
url = '/'
weight = 10

[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'
weight = 20

[[menu.main]]
identifier = 'categories'
name = 'Categories'
url = '/categories/'
weight = 30

[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags/'
weight = 40

[[menu.main]]
identifier = 'contributors'
name = 'Contributors'
url = '/contributors/'
weight = 50

[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 60

[[menu.main]]
identifier = 'search'
name = 'Search'
url = '/search/'
weight = 70

[markup]
[markup.highlight]
noClasses = false
anchorLineNos = false
codeFences = true
guessSyntax = true
lineNos = false
style = 'monokai'

[taxonomies]
category = 'categories'
tag = 'tags'
author = 'authors'
series = 'series'

[outputs]
home = ['HTML', 'RSS', 'JSON']

[params.search]
enable = true
searchContent = true
